### ISSUE TITLE
hidden for user property is ignored.

### ISSUE THREAD

**Issue by begunrom** [Mgiepz/saiku-adhoc#128]
If you specified in your model that a column is hidden ("hidden for user" = true), the column is still shown in the ui, while it isn't in warq.

**Comment by Mgiepz** [comment]
is there an example of this in one of the demo metadatadomains from pentaho? perhaps using joe and suzy?

**Comment by begunrom** [comment]
No, it is not in the standard steel-wheels demo. I have made a small modification on OfficeCode.It should be visible in Employees and not in Offices. I'll send you the metadata.xmi by mail, as i cannot attach it.
