### ISSUE TITLE
Filter breaks report

### ISSUE THREAD

**Issue by ambientbi** [Mgiepz/saiku-adhoc#135]
Based on Orders Meta data.

Add order number to cols,
customer name on groups.

You can see orders for customers. First order should be for customer "AV Stores, Co."

Add customer name to filters and filter for this customer.

Renders blank report

**Comment by Mgiepz** [comment]
please set this:
pt.webdetails.cda.dataaccess.parameterarray.Separator=;

in pentaho-solutions\system\cda\cda.properties
