### ISSUE TITLE
Could not get file properties

### ISSUE THREAD

**Issue by jagnaldo** [Mgiepz/saiku-adhoc#141]
Hi, when i try to share file .adhoc on bi-server, the system display the message 'Could not get file properties'. 
I tried change the files above but didn´t works.: 
1. .../system/saiky-adhoc/plugin.xml In the tag content-generator change the value of the attribute type from "notused" to "saiku-adhoc" 
2. .../system/pentaho.xml in the tag acl-files put the extension adhoc

Bellow the screens:

http://derp.co.uk/99d63

Thanks.

**Comment by Mgiepz** [comment]
change the other contentgenerator to type="adhoc"
in plugin.xml or get latest version

**Comment by jagnaldo** [comment]
OK, works fine !

**Comment by WandersonSangreal** [comment]
Hi, I'm having a similar problem... but in this case, I'm trying to manage the permissions from another application! It works, but this error appear when the number of permissions is large... I think this is associated with acl_position in "pro_acl_list" table, or revision in "pro_files"...

Thanks!
