### ISSUE TITLE
Row Limit dropdown not working

### ISSUE THREAD

**Issue by ghost** [Mgiepz/saiku-adhoc#144]
I installed saiku-adhoc-plugin-1.0-RC1 from 'http://ci.analytical-labs.com/job/saiku-adhoc-plugin/lastSuccessfulBuild/artifact/saiku-adhoc-plugin/target/'

The plugin works but I can't seem to limit my rows. The report will be rendered when I select NONE, but when I try to limit the rows, it won't be rendered.

I get this error in the logs.
2012-04-23 13:49:06,939 ERROR [org.pentaho.platform.web.servlet.GenericServlet] GenericServlet.ERROR_0002 - Could not get content generator: _=1335160146888
javax.servlet.ServletException: Caused by: java.lang.NoSuchMethodError: org.pentaho.metadata.query.model.Query.setLimit(I)V at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:418)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
    at org.codehaus.enunciate.modules.jersey.EnunciateJerseyServletContainer.service(EnunciateJerseyServletContainer.java:239)

I am using BI Server 3.8 and the test data from Steel Wheels.

**Comment by Mgiepz** [comment]
I can reproduce this behaviour in 3.8 stable. But saiku reporting only supports pentaho 3.10 and upwards. There have been a lot of api enhancement when pentaho introduced their enterprise-reporting plugin and we rely on this api with our community plugin.

**Comment by Mgiepz** [comment]
hm, we dont even have the first official stable release. you shouldnt go into production yet.
