### ISSUE TITLE
password exposed

### ISSUE THREAD

**Issue by jortilles** [Mgiepz/saiku-adhoc#146]
Hi.

When you are trying to save a report as .prpt you  must fill the user and password.

the form to do it exposes the password because the inpu type is text instead of password.

In the file:
web/js/templates/editor-templates.htm
in the line 173. Change  the text type

```
input id="exportPassword" type="text"
```

for password tipe

```
input id="exportPassword" type="password"
```

It worked for me

**Comment by Mgiepz** [comment]
good point. this thing is very insecure anyway. but we have to keep it that way until we cut support for biserver 3.10. 
you would still have to provide the log-in information when you open the report in prd though
