### ISSUE TITLE
Filters - Filter by date-field not working

### ISSUE THREAD

**Issue by ghost** [Mgiepz/saiku-adhoc#152]
/*\*  ENGLISH **/

Hello,

When I add a date field (MySql: DATE format "yyyy-MM-dd") to the filter area, and I select the period (example: the 18 June 2012 to June 20, 2012), the results to me returned are incorrect (18 January 2012 19 January 2012) both in English (View -> Language -> English) or French (View -> Language -> French).

Here are the headers of the VALUES are returned to me:

```
Request URL:https://pentaho.xxx.xxx.fr/pentaho/content/saiku-adhoc/rest/query/2809BFA3-D894-86D2-8506-3D5B55EAC16B/FILTER/CATEGORY/Temps/COLUMN/BC_ALL_DIM_DATE_DATEFULL/VALUES
Request Method:POST
Status Code:200 OK

Request Headers :
    POST /pentaho/content/saiku-adhoc/rest/query/2809BFA3-D894-86D2-8506-3D5B55EAC16B/FILTER/CATEGORY/Temps/COLUMN/BC_ALL_DIM_DATE_DATEFULL/VALUES HTTP/1.1
    Host: pentaho.xxx.xxx.fr
    Connection: keep-alive
    Content-Length: 47
    Origin: https://pentaho.xxx.xxx.fr
    X-Requested-With: XMLHttpRequest
    User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5
    Content-Type: application/json
    Accept: application/json, text/javascript, */*; q=0.01
    Referer: https://pentaho.xxx.xxx.fr/pentaho/content/saiku-adhoc/web/index.html?biplugin=true
    Accept-Encoding: gzip,deflate,sdch
    Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
    Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
    Cookie: loginNewWindowChecked=false; JSESSIONID=53B99E5BC1F3E5F5A353188C31A0E813; __utma=250017159.476234670.1328020928.1340197290.1340201503.32; __utmc=250017159; __utmz=250017159.1328020928.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); JSESSIONID=9A694F5EA168A5B7C3161C471DBDDF0D

Request Payload :
    [{"value":"18.06.2012"},{"value":"20.06.2012"}]

Response Headers :
    HTTP/1.1 200 OK
    Server: Apache-Coyote/1.1
    Content-Type: application/json;charset=UTF-8
    Transfer-Encoding: chunked
    Date: Thu, 21 Jun 2012 12:09:55 GMT
```

If you need more information to find a solution to this problem, of course I remain at your disposal;)

/*\* FRANCAIS **/

Bonjour,

Quand j'ajoute un champ date (MySql : format DATE "yyyy-MM-dd") à la zone de filtre, et que je sélectionne la période (exemple : du 18 Juin 2012 au 20 juin 2012), les résultats qui me sont retournés sont incorrects (du 18 Janvier 2012 au 19 Janvier 2012) que ce soit en Anglais (Vue -> Langage -> Anglais) ou en Français (Vue -> Langage -> Français).

Voici les headers de VALUES qui me sont retournés :

```
Request URL:https://pentaho.xxx.xxx.fr/pentaho/content/saiku-adhoc/rest/query/2809BFA3-D894-86D2-8506-3D5B55EAC16B/FILTER/CATEGORY/Temps/COLUMN/BC_ALL_DIM_DATE_DATEFULL/VALUES
Request Method:POST
Status Code:200 OK

Request Headers :
    POST /pentaho/content/saiku-adhoc/rest/query/2809BFA3-D894-86D2-8506-3D5B55EAC16B/FILTER/CATEGORY/Temps/COLUMN/BC_ALL_DIM_DATE_DATEFULL/VALUES HTTP/1.1
    Host: pentaho.xxx.xxx.fr
    Connection: keep-alive
    Content-Length: 47
    Origin: https://pentaho.xxx.xxx.fr
    X-Requested-With: XMLHttpRequest
    User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5
    Content-Type: application/json
    Accept: application/json, text/javascript, */*; q=0.01
    Referer: https://pentaho.xxx.xxx.fr/pentaho/content/saiku-adhoc/web/index.html?biplugin=true
    Accept-Encoding: gzip,deflate,sdch
    Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
    Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
    Cookie: loginNewWindowChecked=false; JSESSIONID=53B99E5BC1F3E5F5A353188C31A0E813; __utma=250017159.476234670.1328020928.1340197290.1340201503.32; __utmc=250017159; __utmz=250017159.1328020928.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); JSESSIONID=9A694F5EA168A5B7C3161C471DBDDF0D

Request Payload :
    [{"value":"18.06.2012"},{"value":"20.06.2012"}]

Response Headers :
    HTTP/1.1 200 OK
    Server: Apache-Coyote/1.1
    Content-Type: application/json;charset=UTF-8
    Transfer-Encoding: chunked
    Date: Thu, 21 Jun 2012 12:09:55 GMT
```

Si vous avez besoin de plus d'information pour trouver une solution à ce problème, je reste évidemment à votre disposition ;)

**Comment by Mgiepz** [comment]
could you please save such a report and show me the content of the .adhoc file? (i.e. through pastebin).
Also please search for the corresponding cda file that is generated. you should find it 
in pentaho-solutions/system/tmp
whith the name 2809BFA3-D894-86D2-8506-3D5B55EAC16B.cda (or whatever your current query id is).
Please post that cda content also

**Comment by ghost** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>

<CDADescriptor>
  <DataSources>
    <Connection id="1" type="metadata.metadata">
      <XmiFile>metadata.xmi</XmiFile>
      <DomainId>Cubes/metadata.xmi</DomainId>
    </Connection>
  </DataSources>
  <DataAccess id="50F2CD94-2F29-2ACD-8035-218E470AD3DC" connection="1" type="mql" access="public">
    <Name>50F2CD94-2F29-2ACD-8035-218E470AD3DC</Name>
    <Query><![CDATA[<?xml version="1.0" encoding="UTF-8"?>

<mql>
  <domain_id>Cubes/metadata.xmi</domain_id>
  <model_id>CHE_MODEL</model_id>
  <options>
    <disable_distinct>false</disable_distinct>
    <limit>-1</limit>
  </options>
  <parameters>
    <parameter defaultValue="" name="F_Temps_BC_ALL_DIM_DATE_DATEFULL_FROM" type="DATE"/>
    <parameter defaultValue="" name="F_Temps_BC_ALL_DIM_DATE_DATEFULL_TO" type="DATE"/>
  </parameters>
  <selections>
    <selection>
      <view>Temps</view>
      <column>BC_ALL_DIM_DATE_DATEFULL</column>
      <aggregation>NONE</aggregation>
    </selection>
    <selection>
      <view>Indicateurs</view>
      <column>BC_CHE_FAC_CONTACTS_NBCONTACTS</column>
      <aggregation>SUM</aggregation>
    </selection>
  </selections>
  <constraints>
    <constraint>
      <operator>AND</operator>
      <condition>[Temps.BC_ALL_DIM_DATE_DATEFULL] &gt; [param:F_Temps_BC_ALL_DIM_DATE_DATEFULL_FROM]</condition>
    </constraint>
    <constraint>
      <operator>AND</operator>
      <condition>[Temps.BC_ALL_DIM_DATE_DATEFULL] &lt; [param:F_Temps_BC_ALL_DIM_DATE_DATEFULL_TO]</condition>
    </constraint>
  </constraints>
  <orders/>
</mql>
]]></Query>
    <Columns>
      <Column idx="0">
        <Name>DateFull</Name>
      </Column>
      <Column idx="1">
        <Name>NbContacts</Name>
      </Column>
    </Columns>
    <Parameters>
      <Parameter name="F_Temps_BC_ALL_DIM_DATE_DATEFULL_FROM" type="Date" pattern="dd.mm.yyyy" default="${TODAY()}"/>
      <Parameter name="F_Temps_BC_ALL_DIM_DATE_DATEFULL_TO" type="Date" pattern="dd.mm.yyyy" default="${TODAY()}"/>
    </Parameters>
  </DataAccess>
</CDADescriptor>
```

**Comment by Mgiepz** [comment]
Hi again!
What exactly do you mean by
"When I add a date field (MySql: DATE format "yyyy-MM-dd") to the filter area" ?
Where exactly is the definition of "yyyy-MM-dd" ?

**Comment by ghost** [comment]
This is the default format of DATE fields in MySQL. By cons, in Pentaho Metadata Editor, I defined the concept in the field the following mask: "EEE dd MMM yyyy"

**Comment by Mgiepz** [comment]
i am able to reproduce the problem now. seems to be a general issue. i will take care of it

**Comment by ghost** [comment]
Thank you!

If you need more information, I remain at your disposal

**Comment by Mgiepz** [comment]
The issue has been fixed. Get the latest ci-build 
http://ci.analytical-labs.com/job/saiku-adhoc-plugin/142/
to verify

**Comment by ghost** [comment]
Thank you!

It actually corrects the problem, but unfortunately it allowed me to see another problem: The start date is not included, as well as the end date, it looks like the use of a BETWEEN, right?

I guess the first seconds are not included, and that the date field does not contain the time stamp, then it looks all that is strictly greater than yyyy-MM-dd 0:00:00 ET strictly less than yyyy -MM-dd 00:00:00, is not it? Unless whether the TimeZone?

**Comment by Mgiepz** [comment]
your assumptions are correct. it truncates the date to 00:00 and it does not take into account timezones. 
I am not sure how this should be accomplished. How would you expect it to work?

**Comment by ghost** [comment]
Can you replace in Constraints : 
    <constraints>
        <constraint>
            <operator>AND</operator>
            <condition>[Temps.BC_ALL_DIM_DATE_DATEFULL] <b>&gt;</b> [param:F_Temps_BC_ALL_DIM_DATE_DATEFULL_FROM]</condition>
        </constraint>
        <constraint>
            <operator>AND</operator>
            <condition>[Temps.BC_ALL_DIM_DATE_DATEFULL] <b>&lt;</b> [param:F_Temps_BC_ALL_DIM_DATE_DATEFULL_TO]</condition>
        </constraint>
    </constraints>

By :  
    <constraints>
        <constraint>
            <operator>AND</operator>
            <condition>[Temps.BC_ALL_DIM_DATE_DATEFULL] <b>&gt;=</b> [param:F_Temps_BC_ALL_DIM_DATE_DATEFULL_FROM]</condition>
        </constraint>
        <constraint>
            <operator>AND</operator>
            <condition>[Temps.BC_ALL_DIM_DATE_DATEFULL] <b>&lt;=</b> [param:F_Temps_BC_ALL_DIM_DATE_DATEFULL_TO]</condition>
        </constraint>
    </constraints>

**Comment by Mgiepz** [comment]
done! i don't have the time to test though

**Comment by ghost** [comment]
It Works !
