### ISSUE TITLE
Problem export PRPT

### ISSUE THREAD

**Issue by jagnaldo** [Mgiepz/saiku-adhoc#158]
Hi Mgiepz,

i´m using Saiku-Adhoc in BI-Server 3.10 and after i exported the report and try to execute it, i receive the error 'Report Validation Failled' ( http://dug.im/53eec)

This is the catalina.out (http://dug.im/3dbe3)

I think the problem is the url with localhost:8080 , my addres is not localhost.

Thanks.

Agnaldo

**Comment by Mgiepz** [comment]
what is the url that you find in the prpt file?
what is your fully qualified url in web.xml?

**Comment by jagnaldo** [comment]
Mgiepz, i can´t open the prpt file (the error: http://dug.im/60685).

Here is my web.xml (http://dug.im/cd16f).

Thanks.

**Comment by Mgiepz** [comment]
could you please try copying saiku-adhoc-core-1.0GA.jar to pentaho/web-inf/lib? restart and check again if the report can be opened in the browser.
to open it in the reportdesigner you need to install the cda-extension in prd.

**Comment by jagnaldo** [comment]
Mgiepz, i copied the  saiku-adhoc-core-1.0GA.jar to the  pentaho/web-inf/lib and tried open the report in the browser but the error occur again. See the screens.
http://dug.im/f980b
http://dug.im/d6bbe
http://dug.im/0b2ac
http://dug.im/9292b

Thanks.

**Comment by Mgiepz** [comment]
this is really odd... did you change anything in saiku-adhoc.properties? theres something in the url that it is calling, that is wrong. i think the "//" does not belong there. 
you should switch to 4.5 as soon as possible to get rid of these http-queries..
you could still try to put
saiku-adhoc.baseurl=http://localhost:8080/pentaho
into saiku-adhoc.properties

anyway the url is allready in the prpt now. you can only change that url by opening it in prd (after you installed the cda-extension)
