### ISSUE TITLE
Problem with filter

### ISSUE THREAD

**Issue by jagnaldo** [Mgiepz/saiku-adhoc#160]
Hi Mgiepz,

i´m having 2 problems with filter component:
1. Values of some categories don´t sort correctly.

http://dug.im/a3f09

In this example, i use 2 columns 'Seguradora' and 'Comarca'

http://dug.im/02f83

The column 'Seguradora' is filtered ok

http://dug.im/1d3f8

The column 'Comarca' is not filtered ok
1. When i choice one value, the result set is empty

http://dug.im/efbe2
http://dug.im/512a5

In this example the filter is ok with column 'Seguradora' 

http://dug.im/08663
http://dug.im/e2c17

In this example the filter is not ok with column 'Comarca'

Here are the tail of catalina.out

http://dug.im/6f874
http://dug.im/7ec9c
http://dug.im/fc7a9
http://dug.im/312a0

Maybe the problem is 'org.saiku.adhoc.exceptions.SaikuAdhocException: Encoding not supported' ????

Thanks 

Agnaldo

**Comment by Mgiepz** [comment]
i am confused why the filter values on your second columns are not sorted in the dialog. did you check the generated cda file? is the query for the filtervalue ok?
where do you see that encoding exception?

**Comment by jagnaldo** [comment]
The problem is exactly this, the columns are not sorted, where i check the cda file ? and the query ? Here is the encoding exception http://dug.im/c5785

**Comment by Mgiepz** [comment]
go to 
pentaho-solutions\system\tmp\
and look for the latest cda file that got created after you ran your report. it should contain your main query and two queries for your parameter values. have a look if there is a sort statement in there.

**Comment by Mgiepz** [comment]
wait.. i just forgot that i fixed this 
https://github.com/Mgiepz/saiku-adhoc/issues/156
maybe this was after your version. you could try using a ci-build.

**Comment by jagnaldo** [comment]
Perfect, works fine !

Thnaks.
