### ISSUE TITLE
Prefiltered Adhoc Reports

### ISSUE THREAD

**Issue by karlhungus** [Mgiepz/saiku-adhoc#162]
I've been looking all over pentaho adhoc reports, as well as saiku-adhoc, and haven't been able to find any features that would allow prefiltering an adhoc query.  I'm thinking of a webservice where I could pass a list of identifiers, or additional conditions to the generated SLQ.

Is there anything that already does this, that I've just missed, or is this the kind of thing i'd have to write myself?

**Comment by Mgiepz** [comment]
This is not possible at the moment. Stuff like that is planned for the next version (probably 2.x) which will be merged with the olap saiku. The idea is to post a json-model to a webservice that returns your report then
