### ISSUE TITLE
Automatic start ad-hoc plugin?

### ISSUE THREAD

**Issue by Dzo67** [Mgiepz/saiku-adhoc#170]
Is it possible to start the Saiku ad-hoc reporting pluging automatic when I log on to the Pentaho portal, so I don't have to push the button first?

**Comment by buggtb** [comment]
Look at CST from webdetails.pt

Tom

On 20/11/2012 11:54, Dzo67 wrote:

> Is it possible to start the Saiku ad-hoc reporting pluging automatic 
> when I log on to the Pentaho portal, so I don't have to push the 
> button first?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Mgiepz/saiku-adhoc/issues/170.

## 

*
   Tom Barber | *Technical Director
-  meteorite***_bi_
-  T: _+44 20 8133 3730 tel:%2B44%2020%208133%203730_ | M: *+44 7921 
  237 727 tel:%2B44%207921%20237%20727
-  W: www.meteorite.bi http://www.meteoritebi/ | Skype: 
  *meteorite.consulting
-  A: *Surrey Technology Centre, Surrey Research Park, Guildford, GU2 
  7YG, UK
  *

*

**Comment by Dzo67** [comment]
Great! It worked after simply following the instructions in the readme and putting the right entry in the cst-config.xml:
"/pentaho/content/saiku-adhoc/web/index.html?biplugin=true#"

Thanks!
