### ISSUE TITLE
Latest code not initializing cda on standalone

### ISSUE THREAD

**Issue by hkazmi** [Mgiepz/saiku-adhoc#187]
Hi Marius, Not sure if you would be able to shed some light. I am trying to run adhoc reports completely stand alone.

The UI comes up, sees the metadata and shows me all the table/columns I want to see, however when I select anything to start a report, I found that pentahoObjectFactory was null (line 539 in PentahoSystem).

I then added PentahoSystem in the saiku-beans definition, now I get pentahoObjectFactory initialzed, however now the "cda" plugin is not found, which is essential. 

Further, I notice SystemPathXmlPluginProvider and FileSystemXmlPluginProvider never get to the processDirectory, which look for the cda plugin.

I have a feeling I am down the wrong path for this thing to get up an running standalone.

Running on tomcat 7.0.53 and JDK 1.6.0_37

Eventual goal is to get saiku analytics and this integrated to give a better suite for BI/reporting.

**Comment by buggtb** [comment]
Hi,

Standalone currently doesn't work, and the BI server plugin is being migrated so it works with Pentaho 5 . Its all very much work in progress and will end up working standalone once more.... just not currently.

Tom

**Comment by hkazmi** [comment]
Hi Tom, thanks for the update, do you want a patch if I get it to work standalone, planning to use 
 LocalCDA to see if that gets me anywhere.

Thanks again.

**Comment by buggtb** [comment]
Our main codebase is now the saiku reporting project, saiku adhoc was the old 1.x code

**Comment by hkazmi** [comment]
Figured that out with a lot of pain :) Working with Saiku Adhoc to get it going :)
