### ISSUE TITLE
Handle timeout during "rendering report" to allow dismissal of modal window

### ISSUE THREAD

**Issue by ghidinelli** [Mgiepz/saiku-adhoc#44]
If a report hangs while being rendered (as just happened for me on the live adhoc.analytical-labs.com demo), the modal window never goes away or times out.  Need to have a handler for connections that fail so you don't have to reload the entire app.

**Comment by Mgiepz** [comment]
this has been solved in the plugin version / ci-build. we will update the standalone demo asap
