### ISSUE TITLE
Templates broken

### ISSUE THREAD

**Issue by jvdongen** [Mgiepz/saiku-adhoc#59]
Template dialog box shows broken links; when clicking on one of them the report generates a 'Null pointer exception' and doesn't display anything anymore. Only way to get rid of this is start all over again

**Comment by buggtb** [comment]
Arse.

**Comment by jvdongen** [comment]
Me? Well thanks! That surely encourages me to file more bugs

Met vriendelijke groet/kind regards,

Jos van Dongen
Tholis Consulting
T +31-(0)50-2304510
M +31-(0)6-51179606
http://www.tholis.com

**Comment by buggtb** [comment]
Midges says i shouldn't rude! Can you believe it. It wasn't aimed at anything apart from the bug, but in  future i shall reply with, Bottom. Better mgie?

**Comment by buggtb** [comment]
fixed will hit the demo server in a couple of hours
